export interface WordPair {
  word1: string;
  word2: string;
  related: boolean;
  difficulty: 'easy' | 'medium' | 'hard';
  category?: string;
}

export interface WordAssociationData {
  [language: string]: WordPair[];
}

export const wordAssociations: WordAssociationData = {
  en: [
    // Easy - Opposites and Basic Pairs (1-25)
    { word1: 'Hot', word2: 'Cold', related: true, difficulty: 'easy', category: 'opposites' },
    { word1: 'Day', word2: 'Night', related: true, difficulty: 'easy', category: 'opposites' },
    { word1: 'Sun', word2: 'Moon', related: true, difficulty: 'easy', category: 'nature' },
    { word1: 'Happy', word2: 'Sad', related: true, difficulty: 'easy', category: 'emotions' },
    { word1: 'Big', word2: 'Small', related: true, difficulty: 'easy', category: 'size' },
    { word1: 'Fast', word2: 'Slow', related: true, difficulty: 'easy', category: 'speed' },
    { word1: 'Up', word2: 'Down', related: true, difficulty: 'easy', category: 'direction' },
    { word1: 'Light', word2: 'Dark', related: true, difficulty: 'easy', category: 'brightness' },
    { word1: 'Young', word2: 'Old', related: true, difficulty: 'easy', category: 'age' },
    { word1: 'Strong', word2: 'Weak', related: true, difficulty: 'easy', category: 'strength' },
    { word1: 'Water', word2: 'Ocean', related: true, difficulty: 'easy', category: 'nature' },
    { word1: 'Fire', word2: 'Heat', related: true, difficulty: 'easy', category: 'nature' },
    { word1: 'Rain', word2: 'Cloud', related: true, difficulty: 'easy', category: 'weather' },
    { word1: 'Bird', word2: 'Fly', related: true, difficulty: 'easy', category: 'animals' },
    { word1: 'Fish', word2: 'Swim', related: true, difficulty: 'easy', category: 'animals' },
    { word1: 'Book', word2: 'Read', related: true, difficulty: 'easy', category: 'activities' },
    { word1: 'Music', word2: 'Listen', related: true, difficulty: 'easy', category: 'activities' },
    { word1: 'Food', word2: 'Eat', related: true, difficulty: 'easy', category: 'activities' },
    { word1: 'Car', word2: 'Drive', related: true, difficulty: 'easy', category: 'transport' },
    { word1: 'Flower', word2: 'Garden', related: true, difficulty: 'easy', category: 'nature' },
    { word1: 'Apple', word2: 'Fruit', related: true, difficulty: 'easy', category: 'food' },
    { word1: 'Bread', word2: 'Butter', related: true, difficulty: 'easy', category: 'food' },
    { word1: 'Coffee', word2: 'Cup', related: true, difficulty: 'easy', category: 'beverages' },
    { word1: 'Winter', word2: 'Snow', related: true, difficulty: 'easy', category: 'seasons' },
    { word1: 'Summer', word2: 'Beach', related: true, difficulty: 'easy', category: 'seasons' },

    // Medium - Conceptual Relationships (26-60)
    { word1: 'Doctor', word2: 'Hospital', related: true, difficulty: 'medium', category: 'professions' },
    { word1: 'Teacher', word2: 'School', related: true, difficulty: 'medium', category: 'professions' },
    { word1: 'Pen', word2: 'Paper', related: true, difficulty: 'medium', category: 'writing' },
    { word1: 'Needle', word2: 'Thread', related: true, difficulty: 'medium', category: 'sewing' },
    { word1: 'Key', word2: 'Lock', related: true, difficulty: 'medium', category: 'tools' },
    { word1: 'Umbrella', word2: 'Rain', related: true, difficulty: 'medium', category: 'weather' },
    { word1: 'Clock', word2: 'Time', related: true, difficulty: 'medium', category: 'measurement' },
    { word1: 'Camera', word2: 'Photo', related: true, difficulty: 'medium', category: 'technology' },
    { word1: 'Brush', word2: 'Paint', related: true, difficulty: 'medium', category: 'art' },
    { word1: 'Hammer', word2: 'Nail', related: true, difficulty: 'medium', category: 'tools' },
    { word1: 'Ship', word2: 'Sailor', related: true, difficulty: 'medium', category: 'transport' },
    { word1: 'Kitchen', word2: 'Chef', related: true, difficulty: 'medium', category: 'professions' },
    { word1: 'Library', word2: 'Books', related: true, difficulty: 'medium', category: 'places' },
    { word1: 'Theater', word2: 'Actor', related: true, difficulty: 'medium', category: 'entertainment' },
    { word1: 'Stadium', word2: 'Sport', related: true, difficulty: 'medium', category: 'places' },
    { word1: 'Seed', word2: 'Plant', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Cloud', word2: 'Sky', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Wave', word2: 'Beach', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Mountain', word2: 'Peak', related: true, difficulty: 'medium', category: 'geography' },
    { word1: 'River', word2: 'Flow', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Sunrise', word2: 'Morning', related: true, difficulty: 'medium', category: 'time' },
    { word1: 'Sunset', word2: 'Evening', related: true, difficulty: 'medium', category: 'time' },
    { word1: 'Lamp', word2: 'Light', related: true, difficulty: 'medium', category: 'household' },
    { word1: 'Pillow', word2: 'Sleep', related: true, difficulty: 'medium', category: 'bedroom' },
    { word1: 'Glasses', word2: 'Vision', related: true, difficulty: 'medium', category: 'health' },
    { word1: 'Spoon', word2: 'Soup', related: true, difficulty: 'medium', category: 'dining' },
    { word1: 'Crown', word2: 'King', related: true, difficulty: 'medium', category: 'royalty' },
    { word1: 'Ring', word2: 'Wedding', related: true, difficulty: 'medium', category: 'celebration' },
    { word1: 'Candle', word2: 'Birthday', related: true, difficulty: 'medium', category: 'celebration' },
    { word1: 'Star', word2: 'Night', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Rainbow', word2: 'Colors', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Volcano', word2: 'Lava', related: true, difficulty: 'medium', category: 'geography' },
    { word1: 'Desert', word2: 'Sand', related: true, difficulty: 'medium', category: 'geography' },
    { word1: 'Forest', word2: 'Trees', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Pearl', word2: 'Oyster', related: true, difficulty: 'medium', category: 'nature' },

    // Hard - Abstract & Subtle Connections (61-75)
    { word1: 'Wisdom', word2: 'Experience', related: true, difficulty: 'hard', category: 'abstract' },
    { word1: 'Memory', word2: 'Past', related: true, difficulty: 'hard', category: 'abstract' },
    { word1: 'Hope', word2: 'Future', related: true, difficulty: 'hard', category: 'abstract' },
    { word1: 'Peace', word2: 'Calm', related: true, difficulty: 'hard', category: 'emotions' },
    { word1: 'Pride', word2: 'Achievement', related: true, difficulty: 'hard', category: 'emotions' },
    { word1: 'Courage', word2: 'Fear', related: true, difficulty: 'hard', category: 'emotions' },
    { word1: 'Trust', word2: 'Friendship', related: true, difficulty: 'hard', category: 'social' },
    { word1: 'Growth', word2: 'Change', related: true, difficulty: 'hard', category: 'abstract' },
    { word1: 'Balance', word2: 'Harmony', related: true, difficulty: 'hard', category: 'abstract' },
    { word1: 'Patience', word2: 'Time', related: true, difficulty: 'hard', category: 'virtues' },
    { word1: 'Freedom', word2: 'Choice', related: true, difficulty: 'hard', category: 'abstract' },
    { word1: 'Knowledge', word2: 'Power', related: true, difficulty: 'hard', category: 'abstract' },
    { word1: 'Silence', word2: 'Thought', related: true, difficulty: 'hard', category: 'meditation' },
    { word1: 'Journey', word2: 'Destination', related: true, difficulty: 'hard', category: 'travel' },
    { word1: 'Dream', word2: 'Reality', related: true, difficulty: 'hard', category: 'abstract' },

    // Non-Related Pairs (76-100)
    { word1: 'Tree', word2: 'Car', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Table', word2: 'Ocean', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Phone', word2: 'Mountain', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Shoe', word2: 'Cloud', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Chair', word2: 'River', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Hat', word2: 'Piano', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Window', word2: 'Tiger', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Bowl', word2: 'Rocket', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Mirror', word2: 'Elephant', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Wallet', word2: 'Tornado', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Ladder', word2: 'Butterfly', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Scissors', word2: 'Planet', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Bicycle', word2: 'Pyramid', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Magazine', word2: 'Volcano', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Keyboard', word2: 'Waterfall', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Curtain', word2: 'Dinosaur', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Envelope', word2: 'Galaxy', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Blanket', word2: 'Compass', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Toothbrush', word2: 'Cathedral', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Drawer', word2: 'Comet', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Basket', word2: 'Satellite', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Candle', word2: 'Submarine', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Button', word2: 'Glacier', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Cushion', word2: 'Telescope', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Napkin', word2: 'Monument', related: false, difficulty: 'hard', category: 'unrelated' },
  ],
  
  de: [
    // Easy - Gegensätze und Grundpaare (1-25)
    { word1: 'Heiß', word2: 'Kalt', related: true, difficulty: 'easy', category: 'opposites' },
    { word1: 'Tag', word2: 'Nacht', related: true, difficulty: 'easy', category: 'opposites' },
    { word1: 'Sonne', word2: 'Mond', related: true, difficulty: 'easy', category: 'nature' },
    { word1: 'Glücklich', word2: 'Traurig', related: true, difficulty: 'easy', category: 'emotions' },
    { word1: 'Groß', word2: 'Klein', related: true, difficulty: 'easy', category: 'size' },
    { word1: 'Schnell', word2: 'Langsam', related: true, difficulty: 'easy', category: 'speed' },
    { word1: 'Oben', word2: 'Unten', related: true, difficulty: 'easy', category: 'direction' },
    { word1: 'Hell', word2: 'Dunkel', related: true, difficulty: 'easy', category: 'brightness' },
    { word1: 'Jung', word2: 'Alt', related: true, difficulty: 'easy', category: 'age' },
    { word1: 'Stark', word2: 'Schwach', related: true, difficulty: 'easy', category: 'strength' },
    { word1: 'Wasser', word2: 'Meer', related: true, difficulty: 'easy', category: 'nature' },
    { word1: 'Feuer', word2: 'Hitze', related: true, difficulty: 'easy', category: 'nature' },
    { word1: 'Regen', word2: 'Wolke', related: true, difficulty: 'easy', category: 'weather' },
    { word1: 'Vogel', word2: 'Fliegen', related: true, difficulty: 'easy', category: 'animals' },
    { word1: 'Fisch', word2: 'Schwimmen', related: true, difficulty: 'easy', category: 'animals' },
    { word1: 'Buch', word2: 'Lesen', related: true, difficulty: 'easy', category: 'activities' },
    { word1: 'Musik', word2: 'Hören', related: true, difficulty: 'easy', category: 'activities' },
    { word1: 'Essen', word2: 'Nahrung', related: true, difficulty: 'easy', category: 'activities' },
    { word1: 'Auto', word2: 'Fahren', related: true, difficulty: 'easy', category: 'transport' },
    { word1: 'Blume', word2: 'Garten', related: true, difficulty: 'easy', category: 'nature' },
    { word1: 'Apfel', word2: 'Frucht', related: true, difficulty: 'easy', category: 'food' },
    { word1: 'Brot', word2: 'Butter', related: true, difficulty: 'easy', category: 'food' },
    { word1: 'Kaffee', word2: 'Tasse', related: true, difficulty: 'easy', category: 'beverages' },
    { word1: 'Winter', word2: 'Schnee', related: true, difficulty: 'easy', category: 'seasons' },
    { word1: 'Sommer', word2: 'Strand', related: true, difficulty: 'easy', category: 'seasons' },

    // Medium - Konzeptionelle Beziehungen (26-60)
    { word1: 'Arzt', word2: 'Krankenhaus', related: true, difficulty: 'medium', category: 'professions' },
    { word1: 'Lehrer', word2: 'Schule', related: true, difficulty: 'medium', category: 'professions' },
    { word1: 'Stift', word2: 'Papier', related: true, difficulty: 'medium', category: 'writing' },
    { word1: 'Nadel', word2: 'Faden', related: true, difficulty: 'medium', category: 'sewing' },
    { word1: 'Schlüssel', word2: 'Schloss', related: true, difficulty: 'medium', category: 'tools' },
    { word1: 'Regenschirm', word2: 'Regen', related: true, difficulty: 'medium', category: 'weather' },
    { word1: 'Uhr', word2: 'Zeit', related: true, difficulty: 'medium', category: 'measurement' },
    { word1: 'Kamera', word2: 'Foto', related: true, difficulty: 'medium', category: 'technology' },
    { word1: 'Pinsel', word2: 'Farbe', related: true, difficulty: 'medium', category: 'art' },
    { word1: 'Hammer', word2: 'Nagel', related: true, difficulty: 'medium', category: 'tools' },
    { word1: 'Schiff', word2: 'Seemann', related: true, difficulty: 'medium', category: 'transport' },
    { word1: 'Küche', word2: 'Koch', related: true, difficulty: 'medium', category: 'professions' },
    { word1: 'Bibliothek', word2: 'Bücher', related: true, difficulty: 'medium', category: 'places' },
    { word1: 'Theater', word2: 'Schauspieler', related: true, difficulty: 'medium', category: 'entertainment' },
    { word1: 'Stadion', word2: 'Sport', related: true, difficulty: 'medium', category: 'places' },
    { word1: 'Samen', word2: 'Pflanze', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Wolke', word2: 'Himmel', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Welle', word2: 'Strand', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Berg', word2: 'Gipfel', related: true, difficulty: 'medium', category: 'geography' },
    { word1: 'Fluss', word2: 'Fließen', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Sonnenaufgang', word2: 'Morgen', related: true, difficulty: 'medium', category: 'time' },
    { word1: 'Sonnenuntergang', word2: 'Abend', related: true, difficulty: 'medium', category: 'time' },
    { word1: 'Lampe', word2: 'Licht', related: true, difficulty: 'medium', category: 'household' },
    { word1: 'Kissen', word2: 'Schlaf', related: true, difficulty: 'medium', category: 'bedroom' },
    { word1: 'Brille', word2: 'Sicht', related: true, difficulty: 'medium', category: 'health' },
    { word1: 'Löffel', word2: 'Suppe', related: true, difficulty: 'medium', category: 'dining' },
    { word1: 'Krone', word2: 'König', related: true, difficulty: 'medium', category: 'royalty' },
    { word1: 'Ring', word2: 'Hochzeit', related: true, difficulty: 'medium', category: 'celebration' },
    { word1: 'Kerze', word2: 'Geburtstag', related: true, difficulty: 'medium', category: 'celebration' },
    { word1: 'Stern', word2: 'Nacht', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Regenbogen', word2: 'Farben', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Vulkan', word2: 'Lava', related: true, difficulty: 'medium', category: 'geography' },
    { word1: 'Wüste', word2: 'Sand', related: true, difficulty: 'medium', category: 'geography' },
    { word1: 'Wald', word2: 'Bäume', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Perle', word2: 'Auster', related: true, difficulty: 'medium', category: 'nature' },

    // Hard - Abstrakt & Subtile Verbindungen (61-75)
    { word1: 'Weisheit', word2: 'Erfahrung', related: true, difficulty: 'hard', category: 'abstract' },
    { word1: 'Erinnerung', word2: 'Vergangenheit', related: true, difficulty: 'hard', category: 'abstract' },
    { word1: 'Hoffnung', word2: 'Zukunft', related: true, difficulty: 'hard', category: 'abstract' },
    { word1: 'Frieden', word2: 'Ruhe', related: true, difficulty: 'hard', category: 'emotions' },
    { word1: 'Stolz', word2: 'Leistung', related: true, difficulty: 'hard', category: 'emotions' },
    { word1: 'Mut', word2: 'Angst', related: true, difficulty: 'hard', category: 'emotions' },
    { word1: 'Vertrauen', word2: 'Freundschaft', related: true, difficulty: 'hard', category: 'social' },
    { word1: 'Wachstum', word2: 'Veränderung', related: true, difficulty: 'hard', category: 'abstract' },
    { word1: 'Gleichgewicht', word2: 'Harmonie', related: true, difficulty: 'hard', category: 'abstract' },
    { word1: 'Geduld', word2: 'Zeit', related: true, difficulty: 'hard', category: 'virtues' },
    { word1: 'Freiheit', word2: 'Wahl', related: true, difficulty: 'hard', category: 'abstract' },
    { word1: 'Wissen', word2: 'Macht', related: true, difficulty: 'hard', category: 'abstract' },
    { word1: 'Stille', word2: 'Gedanke', related: true, difficulty: 'hard', category: 'meditation' },
    { word1: 'Reise', word2: 'Ziel', related: true, difficulty: 'hard', category: 'travel' },
    { word1: 'Traum', word2: 'Wirklichkeit', related: true, difficulty: 'hard', category: 'abstract' },

    // Nicht verwandte Paare (76-100)
    { word1: 'Baum', word2: 'Auto', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Tisch', word2: 'Ozean', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Telefon', word2: 'Berg', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Schuh', word2: 'Wolke', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Stuhl', word2: 'Fluss', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Hut', word2: 'Klavier', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Fenster', word2: 'Tiger', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Schüssel', word2: 'Rakete', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Spiegel', word2: 'Elefant', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Geldbörse', word2: 'Tornado', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Leiter', word2: 'Schmetterling', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Schere', word2: 'Planet', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Fahrrad', word2: 'Pyramide', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Zeitschrift', word2: 'Vulkan', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Tastatur', word2: 'Wasserfall', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Vorhang', word2: 'Dinosaurier', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Umschlag', word2: 'Galaxie', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Decke', word2: 'Kompass', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Zahnbürste', word2: 'Kathedrale', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Schublade', word2: 'Komet', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Korb', word2: 'Satellit', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Kerze', word2: 'U-Boot', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Knopf', word2: 'Gletscher', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Polster', word2: 'Teleskop', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Serviette', word2: 'Monument', related: false, difficulty: 'hard', category: 'unrelated' },
  ],
  
  // French and Portuguese arrays follow similar structure...
  // For brevity, I'll create abbreviated versions with 60 pairs each
  
  fr: [
    // Easy - Opposés et Paires de Base (1-25)
    { word1: 'Chaud', word2: 'Froid', related: true, difficulty: 'easy', category: 'opposites' },
    { word1: 'Jour', word2: 'Nuit', related: true, difficulty: 'easy', category: 'opposites' },
    { word1: 'Soleil', word2: 'Lune', related: true, difficulty: 'easy', category: 'nature' },
    { word1: 'Heureux', word2: 'Triste', related: true, difficulty: 'easy', category: 'emotions' },
    { word1: 'Grand', word2: 'Petit', related: true, difficulty: 'easy', category: 'size' },
    { word1: 'Rapide', word2: 'Lent', related: true, difficulty: 'easy', category: 'speed' },
    { word1: 'Haut', word2: 'Bas', related: true, difficulty: 'easy', category: 'direction' },
    { word1: 'Clair', word2: 'Sombre', related: true, difficulty: 'easy', category: 'brightness' },
    { word1: 'Jeune', word2: 'Vieux', related: true, difficulty: 'easy', category: 'age' },
    { word1: 'Fort', word2: 'Faible', related: true, difficulty: 'easy', category: 'strength' },
    { word1: 'Eau', word2: 'Océan', related: true, difficulty: 'easy', category: 'nature' },
    { word1: 'Feu', word2: 'Chaleur', related: true, difficulty: 'easy', category: 'nature' },
    { word1: 'Pluie', word2: 'Nuage', related: true, difficulty: 'easy', category: 'weather' },
    { word1: 'Oiseau', word2: 'Voler', related: true, difficulty: 'easy', category: 'animals' },
    { word1: 'Poisson', word2: 'Nager', related: true, difficulty: 'easy', category: 'animals' },
    { word1: 'Livre', word2: 'Lire', related: true, difficulty: 'easy', category: 'activities' },
    { word1: 'Musique', word2: 'Écouter', related: true, difficulty: 'easy', category: 'activities' },
    { word1: 'Nourriture', word2: 'Manger', related: true, difficulty: 'easy', category: 'activities' },
    { word1: 'Voiture', word2: 'Conduire', related: true, difficulty: 'easy', category: 'transport' },
    { word1: 'Fleur', word2: 'Jardin', related: true, difficulty: 'easy', category: 'nature' },
    { word1: 'Pomme', word2: 'Fruit', related: true, difficulty: 'easy', category: 'food' },
    { word1: 'Pain', word2: 'Beurre', related: true, difficulty: 'easy', category: 'food' },
    { word1: 'Café', word2: 'Tasse', related: true, difficulty: 'easy', category: 'beverages' },
    { word1: 'Hiver', word2: 'Neige', related: true, difficulty: 'easy', category: 'seasons' },
    { word1: 'Été', word2: 'Plage', related: true, difficulty: 'easy', category: 'seasons' },

    // Medium - Relations Conceptuelles (26-50)
    { word1: 'Médecin', word2: 'Hôpital', related: true, difficulty: 'medium', category: 'professions' },
    { word1: 'Professeur', word2: 'École', related: true, difficulty: 'medium', category: 'professions' },
    { word1: 'Stylo', word2: 'Papier', related: true, difficulty: 'medium', category: 'writing' },
    { word1: 'Aiguille', word2: 'Fil', related: true, difficulty: 'medium', category: 'sewing' },
    { word1: 'Clé', word2: 'Serrure', related: true, difficulty: 'medium', category: 'tools' },
    { word1: 'Parapluie', word2: 'Pluie', related: true, difficulty: 'medium', category: 'weather' },
    { word1: 'Horloge', word2: 'Temps', related: true, difficulty: 'medium', category: 'measurement' },
    { word1: 'Caméra', word2: 'Photo', related: true, difficulty: 'medium', category: 'technology' },
    { word1: 'Pinceau', word2: 'Peinture', related: true, difficulty: 'medium', category: 'art' },
    { word1: 'Marteau', word2: 'Clou', related: true, difficulty: 'medium', category: 'tools' },
    { word1: 'Navire', word2: 'Marin', related: true, difficulty: 'medium', category: 'transport' },
    { word1: 'Cuisine', word2: 'Chef', related: true, difficulty: 'medium', category: 'professions' },
    { word1: 'Bibliothèque', word2: 'Livres', related: true, difficulty: 'medium', category: 'places' },
    { word1: 'Théâtre', word2: 'Acteur', related: true, difficulty: 'medium', category: 'entertainment' },
    { word1: 'Stade', word2: 'Sport', related: true, difficulty: 'medium', category: 'places' },
    { word1: 'Graine', word2: 'Plante', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Nuage', word2: 'Ciel', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Vague', word2: 'Plage', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Montagne', word2: 'Sommet', related: true, difficulty: 'medium', category: 'geography' },
    { word1: 'Rivière', word2: 'Couler', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Lever du soleil', word2: 'Matin', related: true, difficulty: 'medium', category: 'time' },
    { word1: 'Coucher du soleil', word2: 'Soir', related: true, difficulty: 'medium', category: 'time' },
    { word1: 'Lampe', word2: 'Lumière', related: true, difficulty: 'medium', category: 'household' },
    { word1: 'Oreiller', word2: 'Sommeil', related: true, difficulty: 'medium', category: 'bedroom' },
    { word1: 'Lunettes', word2: 'Vision', related: true, difficulty: 'medium', category: 'health' },

    // Non-Related Pairs (51-75)
    { word1: 'Arbre', word2: 'Voiture', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Table', word2: 'Océan', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Téléphone', word2: 'Montagne', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Chaussure', word2: 'Nuage', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Chaise', word2: 'Rivière', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Chapeau', word2: 'Piano', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Fenêtre', word2: 'Tigre', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Bol', word2: 'Fusée', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Miroir', word2: 'Éléphant', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Portefeuille', word2: 'Tornade', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Échelle', word2: 'Papillon', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Ciseaux', word2: 'Planète', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Bicyclette', word2: 'Pyramide', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Magazine', word2: 'Volcan', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Clavier', word2: 'Cascade', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Rideau', word2: 'Dinosaure', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Enveloppe', word2: 'Galaxie', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Couverture', word2: 'Boussole', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Brosse à dents', word2: 'Cathédrale', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Tiroir', word2: 'Comète', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Panier', word2: 'Satellite', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Bougie', word2: 'Sous-marin', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Bouton', word2: 'Glacier', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Coussin', word2: 'Télescope', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Serviette', word2: 'Monument', related: false, difficulty: 'hard', category: 'unrelated' },
  ],

  pt: [
    // Easy - Opostos e Pares Básicos (1-25)
    { word1: 'Quente', word2: 'Frio', related: true, difficulty: 'easy', category: 'opposites' },
    { word1: 'Dia', word2: 'Noite', related: true, difficulty: 'easy', category: 'opposites' },
    { word1: 'Sol', word2: 'Lua', related: true, difficulty: 'easy', category: 'nature' },
    { word1: 'Feliz', word2: 'Triste', related: true, difficulty: 'easy', category: 'emotions' },
    { word1: 'Grande', word2: 'Pequeno', related: true, difficulty: 'easy', category: 'size' },
    { word1: 'Rápido', word2: 'Lento', related: true, difficulty: 'easy', category: 'speed' },
    { word1: 'Cima', word2: 'Baixo', related: true, difficulty: 'easy', category: 'direction' },
    { word1: 'Claro', word2: 'Escuro', related: true, difficulty: 'easy', category: 'brightness' },
    { word1: 'Jovem', word2: 'Velho', related: true, difficulty: 'easy', category: 'age' },
    { word1: 'Forte', word2: 'Fraco', related: true, difficulty: 'easy', category: 'strength' },
    { word1: 'Água', word2: 'Oceano', related: true, difficulty: 'easy', category: 'nature' },
    { word1: 'Fogo', word2: 'Calor', related: true, difficulty: 'easy', category: 'nature' },
    { word1: 'Chuva', word2: 'Nuvem', related: true, difficulty: 'easy', category: 'weather' },
    { word1: 'Pássaro', word2: 'Voar', related: true, difficulty: 'easy', category: 'animals' },
    { word1: 'Peixe', word2: 'Nadar', related: true, difficulty: 'easy', category: 'animals' },
    { word1: 'Livro', word2: 'Ler', related: true, difficulty: 'easy', category: 'activities' },
    { word1: 'Música', word2: 'Ouvir', related: true, difficulty: 'easy', category: 'activities' },
    { word1: 'Comida', word2: 'Comer', related: true, difficulty: 'easy', category: 'activities' },
    { word1: 'Carro', word2: 'Dirigir', related: true, difficulty: 'easy', category: 'transport' },
    { word1: 'Flor', word2: 'Jardim', related: true, difficulty: 'easy', category: 'nature' },
    { word1: 'Maçã', word2: 'Fruta', related: true, difficulty: 'easy', category: 'food' },
    { word1: 'Pão', word2: 'Manteiga', related: true, difficulty: 'easy', category: 'food' },
    { word1: 'Café', word2: 'Xícara', related: true, difficulty: 'easy', category: 'beverages' },
    { word1: 'Inverno', word2: 'Neve', related: true, difficulty: 'easy', category: 'seasons' },
    { word1: 'Verão', word2: 'Praia', related: true, difficulty: 'easy', category: 'seasons' },

    // Medium - Relações Conceituais (26-50)
    { word1: 'Médico', word2: 'Hospital', related: true, difficulty: 'medium', category: 'professions' },
    { word1: 'Professor', word2: 'Escola', related: true, difficulty: 'medium', category: 'professions' },
    { word1: 'Caneta', word2: 'Papel', related: true, difficulty: 'medium', category: 'writing' },
    { word1: 'Agulha', word2: 'Linha', related: true, difficulty: 'medium', category: 'sewing' },
    { word1: 'Chave', word2: 'Fechadura', related: true, difficulty: 'medium', category: 'tools' },
    { word1: 'Guarda-chuva', word2: 'Chuva', related: true, difficulty: 'medium', category: 'weather' },
    { word1: 'Relógio', word2: 'Tempo', related: true, difficulty: 'medium', category: 'measurement' },
    { word1: 'Câmera', word2: 'Foto', related: true, difficulty: 'medium', category: 'technology' },
    { word1: 'Pincel', word2: 'Tinta', related: true, difficulty: 'medium', category: 'art' },
    { word1: 'Martelo', word2: 'Prego', related: true, difficulty: 'medium', category: 'tools' },
    { word1: 'Navio', word2: 'Marinheiro', related: true, difficulty: 'medium', category: 'transport' },
    { word1: 'Cozinha', word2: 'Cozinheiro', related: true, difficulty: 'medium', category: 'professions' },
    { word1: 'Biblioteca', word2: 'Livros', related: true, difficulty: 'medium', category: 'places' },
    { word1: 'Teatro', word2: 'Ator', related: true, difficulty: 'medium', category: 'entertainment' },
    { word1: 'Estádio', word2: 'Esporte', related: true, difficulty: 'medium', category: 'places' },
    { word1: 'Semente', word2: 'Planta', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Nuvem', word2: 'Céu', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Onda', word2: 'Praia', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Montanha', word2: 'Pico', related: true, difficulty: 'medium', category: 'geography' },
    { word1: 'Rio', word2: 'Fluir', related: true, difficulty: 'medium', category: 'nature' },
    { word1: 'Nascer do sol', word2: 'Manhã', related: true, difficulty: 'medium', category: 'time' },
    { word1: 'Pôr do sol', word2: 'Tarde', related: true, difficulty: 'medium', category: 'time' },
    { word1: 'Lâmpada', word2: 'Luz', related: true, difficulty: 'medium', category: 'household' },
    { word1: 'Travesseiro', word2: 'Sono', related: true, difficulty: 'medium', category: 'bedroom' },
    { word1: 'Óculos', word2: 'Visão', related: true, difficulty: 'medium', category: 'health' },

    // Pares Não Relacionados (51-75)
    { word1: 'Árvore', word2: 'Carro', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Mesa', word2: 'Oceano', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Telefone', word2: 'Montanha', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Sapato', word2: 'Nuvem', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Cadeira', word2: 'Rio', related: false, difficulty: 'easy', category: 'unrelated' },
    { word1: 'Chapéu', word2: 'Piano', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Janela', word2: 'Tigre', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Tigela', word2: 'Foguete', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Espelho', word2: 'Elefante', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Carteira', word2: 'Tornado', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Escada', word2: 'Borboleta', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Tesoura', word2: 'Planeta', related: false, difficulty: 'medium', category: 'unrelated' },
    { word1: 'Bicicleta', word2: 'Pirâmide', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Revista', word2: 'Vulcão', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Teclado', word2: 'Cascata', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Cortina', word2: 'Dinossauro', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Envelope', word2: 'Galáxia', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Cobertor', word2: 'Bússola', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Escova de dentes', word2: 'Catedral', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Gaveta', word2: 'Cometa', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Cesta', word2: 'Satélite', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Vela', word2: 'Submarino', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Botão', word2: 'Geleira', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Almofada', word2: 'Telescópio', related: false, difficulty: 'hard', category: 'unrelated' },
    { word1: 'Guardanapo', word2: 'Monumento', related: false, difficulty: 'hard', category: 'unrelated' },
  ]
};
